### ISSUE TITLE
iOS: popover's fixed position borks when keyboard shows

### ISSUE THREAD

**Issue by nickvelloff** [the-grid/ed#101]
Perhaps a z-index issue?
![ed-link-publish-buttons](https://cloud.githubusercontent.com/assets/885369/13420172/edbded62-df38-11e5-9b28-39cc737a78a9.gif)

**Comment by forresto** [comment]
Might be a material-ui issue, fixed in upcoming:
http://www.material-ui.com/v0.15.0-alpha.1/#/components/popover

Current, broken on my ipad: http://www.material-ui.com/v0.14.4/#/components/popover

Also, autofocusing the first field might be part of the issue, since the keyboard jumps up and changes the positioning. 

---

Yeah... I think the keyboard jump makes MUI think that we've scrolled away :expressionless: 

---

https://github.com/callemall/material-ui/pull/3144 :apple: `fixed` again (ಠ_ಠ) /// MUI15a1 doesn't fix the issue.

**Comment by forresto** [comment]
Rebass work in #107 will make this moot.

**Comment by forresto** [comment]
Fixed with Rebass.
