### ISSUE TITLE
Should onShareUrl be triggered multiple times?

### ISSUE THREAD

**Issue by hannesstruss** [the-grid/ed#48]
Steps to reproduce:
1. Hit enter to create new block
2. Paste URL, hit enter
3. `onShareUrl` callback is called (we don't do anything with it for now)
4. Move caret to end of pasted URL
5. Hit enter
6. `onShareUrl` is called again
7. `GOTO 4`

I'm not sure this is a real-world-problem. But what if I want a block that just contains a plain-text url without sharing it?

**Comment by forresto** [comment]
Once you [replace the url block with a placeholder](https://github.com/the-grid/ed/blob/f495365901457c60333de45c9088b36068965f50/demo/demo.js#L86-L98) 4 isn't possible.

A line with only a url always gets shared. If this turns out to be an issue, it could not `trim()` the line for the url test, so `url + space + return` would not get shared.

**Comment by hannesstruss** [comment]
thanks!
