### ISSUE TITLE
Separation of concerns: Placeholder creation spread across App and Ed

### ISSUE THREAD

**Issue by hannesstruss** [the-grid/ed#70]
Currently, when sharing URLs, Ed creates the placeholder. For sharing images, there is `ed.insertBlocks(index, blocks)`, which requires the app to create the placeholders itself.

I think for consistency it should only be one component's responsibility to actually construct placeholder blocks. Currently, the knowledge about placeholder construction, the placeholder block's internal structure (`metadata.status` etc.) is spread across app and Ed. Since Ed has to interpret placeholder blocks anyway, it should be the single source of construction as well. I'd encapsulate that behind a more narrowly scoped API like (a less verbose version of) `ed.createPlaceholdersForImages(originalPlaceholderBlockId, numberOfPlaceholders)` which could return an array of placeholder block IDs to share into. 

Let's discuss that in the meeting suggested in #editor!

cc @nickvelloff

**Comment by forresto** [comment]
That's easy enough. Making it work with `setContent` was @JohnRandom's ask to keep the flow fluxy. Convenience methods like these are fine to add on top for apps. Would be more like

`ed.createPlaceholders(index, count)`

Since app only has the index at that point, and placeholders are the same for files and urls (though we could add cover via data url in future). 

Going down this path (apps don't munge blocks), would you also want 
`ed.updatePlaceholder(id, {status, progress})`

**Comment by hannesstruss** [comment]
@forresto yeah, that sounds good! Should also be easier to document and decreases API surface. I'd also recommend everyone else to use those APIs and write a little boilerplate to adapt them to their own architecture :)

**Comment by nickvelloff** [comment]
:+1: :+1: :+1:

**Comment by JohnRandom** [comment]
I think I mentioned this solution when we were talking about it in Berlin. Back then, no one wanted this API in addition to the way I proposed for Flux. Happy to see you adopted it anyway.
